# Generated by Django 2.1.2 on 2018-12-04 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Visitor'),
        ),
    ]
